### ISSUE TITLE
please update this and package . so many errors

### ISSUE THREAD

**Issue by ptpmashish** [bwhybrow23/Nginx#2]

**Comment by ptpmashish** [comment]
please update the read me and how to uninstall. tried so many times. its not going

when i run nginx -t it doesnt check the syntax its asking me to choose options which is creating chaos

**Comment by ptpmashish** [comment]
finally had to do this to remove. sudo npm uninstall -g nginx

it was not letting me use the normal nginx and was interfering with nginx commands

**Comment by bwhybrow23** [comment]
I should really include in the ReadMe that this is still in development.

**Comment by bwhybrow23** [comment]
NPM page has been updated to show that the package is still in development alongside a new "Known Bugs" section. Apologies for the inconvenience
